version: '3.7'

services:

  service-database:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    networks:
      - sum-services-networks
    environment: 
      POSTGRES_DB: sum_database
      POSTGRES_PASSWORD: d2cb1d0af058c7521c27a3aa5ad78dfd

  config-server:
    image: myuquilima/config-server
    ports:
      - "8888:8888"
    restart: always
    networks:
      - sum-services-networks

  discover-server:
    image: myuquilima/discovery-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      - sum-services-networks

  users-service:
    image: myuquilima/users-service
    ports:
      - "8082:8082"
    restart: always
    networks:
      - sum-services-networks
    depends_on:
      - config-server
      - discover-server
      - service-database

  oauth-server:
    image: myuquilima/oauth-server
    ports:
      - "9100:9100"
    restart: always
    networks:
      - sum-services-networks
    depends_on:
      - config-server
      - discover-server
      - users-service

  sum-service:
    image: myuquilima/sum-service
    ports:
      - "8083:8083"
    restart: always
    networks:
      - sum-services-networks
    depends_on:
      - config-server
      - discover-server
      - service-database
      - oauth-server

  proxy-server:
    image: myuquilima/proxy-server
    ports:
      - "8090:8090"
    restart: always
    networks:
      - sum-services-networks
    depends_on:
      - config-server
      - discover-server
      - sum-service
      - oauth-server
      - users-service

networks:
  sum-services-networks: